Profile system
OmegaOoh/ku-tangtee pull request #151
Opened 2024-10-31 14:20 UTC by TeerapatTrepopsakulsin

### Description

- Profile features
    + create profile
    + show profile
    + edit profile
- Profile pages
    + profile index `/profile` (profile:index): show only user's profile, if created,/create profile feature.
    + profile detail `/profile/<profile.id>` (profile:detail):  show user's profile according to parameter `profile.id`/ edit profile feature.

### Functional Acceptance Criteria

- Backend works:
    + Show, Create, Edit features works according to the request (tested)
    + has_profile data when `GET /profile` (tested)
    + User cannot create profile twice (tested)
    + Cannot edit other user profile (tested)

### Checklist 

- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### Additional Information
- `/profile`
    + GET - show user profile and `has_profile` status
    + POST - create profile
- `/profile/<profile.id>`
    + GET - show profile according to `profile.id`
    + PUT - edit profile (only profile owner can)
- Don't forget to _migrate_

2024-10-31 14:27 UTC, OmegaOoh requested changes
I saw some problem with it, please resolve before request for rereview

2024-10-31 14:27 UTC, OmegaOoh commented on profiles/models.py
I said no DoB, unless you can justify it

2024-10-31 14:27 UTC, OmegaOoh commented on profiles/serializer/model_serializers.py
Undescriptive Classdocstrings

2024-10-31 14:27 UTC, OmegaOoh commented on profiles/serializer/permissions.py
Bad ClassName as we discussed on Code Review

2024-10-31 14:55 UTC, TeerapatTrepopsakulsin commented on profiles/models.py
- Some activities may involve age restriction (e.g. Bar)
- Birthday party, maybe

2024-10-31 15:16 UTC, TeerapatTrepopsakulsin commented on profiles/serializer/model_serializers.py
Edited.

2024-10-31 15:16 UTC, TeerapatTrepopsakulsin commented on profiles/serializer/permissions.py
Thanks for mentioning. Edited.

2024-10-31 16:19 UTC, OmegaOoh commented on profiles/models.py
Not Approved. Please Delete it

2024-11-01 15:07 UTC, TeerapatTrepopsakulsin commented
Last `makemigrations` create activities migration file (0005)

2024-11-01 15:08 UTC, OmegaOoh approved these changes
Good job. Approved

2024-11-01 15:31 UTC, opxz7148 approved these changes
Good job. User profile has useful information as we plan. _Approve_

2024-11-01 15:33 UTC, merged