Activity Location backend and is_cancelled Field
OmegaOoh/ku-tangtee pull request #216
Opened 2024-11-13 04:32 UTC by TeerapatTrepopsakulsin

### Description

- #207 
- #208 

### Functional Acceptance Criteria

- Can create and edit activity to update attribute correctly as state in _Additional Information_

### Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation, if applicable.
- [x] My code follows the Coding Guidelines.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Other (please specify)

### Additional Information
- Don't forget to _migrate_
- `Location`: _new_  model
  + `latitude`/`longitude`: DecimalField
  + Edit/Create activity with data `{'location': {'lat': <latitude>, 'lon':<longitude>}}` to set the value
  + location of the activity is `activity.location_set.first()`
- `Activity`
  - `on_site`: BooleanField, default is False
    + Edit/Create activity with data `{'on_site': bool}` to set the value
  - `is_cancelled`: BooleanField, default is False
    + True if the activity is cancelled
    + `is_active()` is False if `is_cancelled` is True
    + Edit activity with data `{'is_cancelled': bool}` to set the value

2024-11-14 02:53 UTC, OmegaOoh reviewed
Just want to let you know, there's more than one place I put the test data in. Another one is in `Edit Modal`

2024-11-14 06:08 UTC, OmegaOoh requested changes
You need to wait for @Thanawas-Sirilertsathit for functionality of the apps but the codes most of it looks fine (not worth a wait though) and you need to address the concerns I write below.

2024-11-14 06:08 UTC, OmegaOoh commented on activities/models.py
2 Concerns here,
1. Why did you `from twisted.protocols.amp import Decimal` (also you didn't specify it in `requirements.txt` which you should
2. Location needed to not know about the activity. Activity is the one store's location.

2024-11-14 06:08 UTC, OmegaOoh commented on activities/views/activity_detail.py
Please remove dispensable comments.

2024-11-14 07:27 UTC, Thanawas-Sirilertsathit requested changes
Merge from main please so that I can know that location model is working or not

2024-11-14 07:38 UTC, Thanawas-Sirilertsathit commented
Sorry for that, the previous activities don't work but newly created activities work well

2024-11-14 07:41 UTC, Thanawas-Sirilertsathit approved these changes
Functionality works well for newly created activities although it no longer supports the previous activities.

2024-11-14 17:00 UTC, TeerapatTrepopsakulsin commented on activities/models.py
1) deleted
2) Modified
3) deleted

2024-11-15 03:46 UTC, OmegaOoh requested changes

2024-11-15 03:46 UTC, OmegaOoh commented on activities/views/util.py
> +from email.policy import default
What is this used for

2024-11-15 03:55 UTC, TeerapatTrepopsakulsin commented on activities/views/util.py
> +from email.policy import default
Accidentally added it.
Removed.

2024-11-15 03:59 UTC, OmegaOoh approved these changes

2024-11-15 06:17 UTC, Thanawas-Sirilertsathit commented
Functionality checked, your work is compatible with the frontend well.

2024-11-15 06:49 UTC, merged