Create associated class
OmegaOoh/ku-tangtee pull request #55
Opened 2024-10-09 12:48 UTC by opxz7148

# DONT MERGE THIS BRANCH YET
Note: 
- I have create a new model Attend to store which user attend each activity.
- I have revise create activity accord to new models.
- I have revise join to but right now user can still able to join activity that they've join already so this must be fix.
- I've revise some of test but not all. Test file with _ in a front of a file name is a one that I'm not yet revise.
- I've shortcut function but look like it more verbose should fix it's later.

2024-10-10 15:59 UTC, opxz7148 commented
Already fetch code from main. I've edit @Thanawas-Sirilertsathit  code on edit activity handler function. From now on user can't edit number of people anymore accord to new models. From front end view there're no need to change since edit activity just simply ignore people value from post req.

2024-10-11 01:32 UTC, OmegaOoh commented
> Already fetch code from main. I've edit @Thanawas-Sirilertsathit code on edit activity handler function. From now on user can't edit number of people anymore accord to new models. From front end view there're no need to change since edit activity just simply ignore people value from post req.

You should says "its no need to change the API usage." instead of "From front end view there're no need to change" as it can be misunderstand.

2024-10-11 01:44 UTC, OmegaOoh requested changes
If the response from create activity won't be used/ is reassigned by another response without usage, assign it to `_` or just simply remove it from return of the function, which I don't see the use case of it at the moment

2024-10-11 01:44 UTC, OmegaOoh commented on activities/tests/test_index.py
Please explain the reason for commenting test cases

2024-10-11 01:45 UTC, Thanawas-Sirilertsathit commented
I didn't login yet but pressed join and it joined. After login it still said I already joined.

2024-10-11 01:57 UTC, opxz7148 commented on activities/tests/test_index.py
I'm just forget to uncomment It. Already fix.

2024-10-11 02:03 UTC, opxz7148 commented
> If the response from create activity won't be used/ is reassigned by another response without usage, assign it to `_` or just simply remove it from return of the function, which I don't see the use case of it at the moment

Respond from create activity still necessary in some test case. Mostly in create activity test.

2024-10-11 03:07 UTC, OmegaOoh requested changes

2024-10-11 03:07 UTC, OmegaOoh commented on activities/tests/test_detail.py
response from create_activity has not been used and reassigned immediately after the initial assignment

2024-10-11 03:07 UTC, OmegaOoh commented on activities/tests/test_join.py
This file also contains unused response from create_activity

2024-10-11 03:07 UTC, OmegaOoh commented on activities/tests/test_index.py
This file contains multiple unused response from create_activity

2024-10-11 03:07 UTC, OmegaOoh commented on activities/tests/test_join.py
> +        response, new_act = create_activity()
This response is redundant

2024-10-11 03:08 UTC, OmegaOoh commented
> > If the response from create activity won't be used/ is reassigned by another response without usage, assign it to `_` or just simply remove it from return of the function, which I don't see the use case of it at the moment
> 
> Respond from create activity still necessary in some test case. Mostly in create activity test.

Don't make me comment every other one of them

2024-10-11 13:21 UTC, OmegaOoh approved these changes
Good job, Go ahead and merge it

2024-10-11 14:14 UTC, merged