Showing profile picture in base template + Index page shows description of activity only 2 lines
OmegaOoh/ku-tangtee pull request #64
Opened 2024-10-14 11:43 UTC by Thanawas-Sirilertsathit

- Dropdown feature in base template header using profile picture and name.
- Index page shows description of activity only 2 lines after that it will be ...
- Profile picture will only be shown when login.

2024-10-14 12:29 UTC, OmegaOoh requested changes
I tried on newly created database and got this error
![Notfound Error](https://github.com/user-attachments/assets/2a5b9640-53ae-4635-9854-1894d49472aa)

The color of dropdown is hard to read.
use `base-300` as dropdown color and `neutral` as the color while hover. 

also change the view to use REST Framework.

2024-10-14 13:47 UTC, Thanawas-Sirilertsathit commented
> I tried on newly created database and got this error ![Notfound Error](https://private-user-images.githubusercontent.com/71599562/376237829-2a5b9640-53ae-4635-9854-1894d49472aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTI3NTksIm5iZiI6MTcyODkxMjQ1OSwicGF0aCI6Ii83MTU5OTU2Mi8zNzYyMzc4MjktMmE1Yjk2NDAtNTNhZS00NjM1LTk4NTQtMTg5NGQ0OTQ3MmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEzMjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNThiMjg0NDE1ZTljOTY0ZDc1NzFhNzA1ZWM4YTg5ZjEwYWRmOTQ0YjE2ZGFkZDlmMTA3NTUxODVjNjViYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bYdi3Kd2mpv8AqRkAQ8w7LR4WSj-siaq7UKhsO5EEUE)
> 
> The color of dropdown is hard to read. use `base-300` as dropdown color and `neutral` as the color while hover.
> 
> also change the view to use REST Framework.

I don't see any Runtime error. I tried creating new database already, it can show profile picture correctly.

2024-10-14 13:51 UTC, Thanawas-Sirilertsathit commented
I got only 403, 400 when forgot to setup SITE correctly

2024-10-17 03:30 UTC, OmegaOoh requested changes

2024-10-17 03:30 UTC, OmegaOoh commented on mysite/views.py
> +        social_account = SocialAccount.objects.get(user=user, provider=OAUTH_PROVIDER)
You can remove provider, we got only 1. If you consider remove this you may need to remove OAUTH_PROVIDER from `settings.py` and `sample.env` also

2024-10-17 03:56 UTC, OmegaOoh commented on mysite/views.py
> +        social_account = SocialAccount.objects.get(user=user, provider=OAUTH_PROVIDER)
@opxz7148 [fixed it.](https://github.com/OmegaOoh/ku-tangtee/pull/64/commits/521eafdb83c009e0b5591ab5e9a4bec6137b6cd4)

2024-10-17 03:58 UTC, OmegaOoh requested changes
sample.env and settings.py still contiains unused OAUTH_PROVIDER.

2024-10-17 04:27 UTC, opxz7148 approved these changes
Look good

2024-10-17 05:08 UTC, TeerapatTrepopsakulsin reviewed
- Dropdown feature in base template header using profile picture and name. _Approve_
- Index page shows description of activity only 2 lines after that it will be ...
test case:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
got:
![image](https://github.com/user-attachments/assets/2792fd1d-4549-443a-89e8-21fa5b32b41a)

- Profile picture will only be shown when login. _Approve_

2024-10-17 06:27 UTC, Thanawas-Sirilertsathit commented
I mean in Activity Index page detail will be shorten to 2 lines

2024-10-17 06:28 UTC, Thanawas-Sirilertsathit commented
I will fix the Activity Detail page when I have to do profile pic of participants.

2024-10-17 09:11 UTC, OmegaOoh approved these changes

2024-10-17 15:46 UTC, opxz7148 approved these changes
Somehow its profile pic doesn't appear on Firefox. But it's work for chrome but I think it's good to merge.

2024-10-17 15:46 UTC, merged