Rest framework conversion
OmegaOoh/ku-tangtee pull request #84
Opened 2024-10-17 09:24 UTC by opxz7148

Reopen after PR close cause by renaming

2024-10-18 16:48 UTC, opxz7148 commented
@TeerapatTrepopsakulsin You haven't change url reverse inside test pls change it and modify test case accordingly. Also there are join handler that haven't convert to REST yet. I've plan to do it myself tmr but I change my mind to go to health activity. Since you have time tomorrow pls convert that to rest too, by make class ActivityDetail handle POST request. Also don't forget to merge main and resolve conflict.

2024-10-19 09:37 UTC, TeerapatTrepopsakulsin commented
- Change the URLs of the view to the new ones that use the REST framework.
- Request detail
    - Index: GET - Show list of activities, POST - Create activity
    - Detail: GET - Show activity detail, POST - Join activity, PUT - Edit activity

- Revise the tests to use new URLs.

2024-10-19 11:36 UTC, Thanawas-Sirilertsathit commented
![image](https://github.com/user-attachments/assets/b4f4ad16-7881-45bc-be81-924933812f5e)
![image](https://github.com/user-attachments/assets/d0e15a92-92ab-40f1-960f-6ee66dcc5afd)
Does these backend stuffs work with edit page? I got error 404.

2024-10-19 12:03 UTC, OmegaOoh commented
> ![image](https://private-user-images.githubusercontent.com/146911997/378075612-b4f4ad16-7881-45bc-be81-924933812f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzkzNzUsIm5iZiI6MTcyOTMzOTA3NSwicGF0aCI6Ii8xNDY5MTE5OTcvMzc4MDc1NjEyLWI0ZjRhZDE2LTc4ODEtNDViYy1iZTgxLTkyNDkzMzgxMmY1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMTU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmMyOTg1MzI0N2EwZTUwMjViZTlkY2Y1NmQ2NTUwYzhmZmJiZmEwYWUwM2JkYjRhYjU2OTdjZmY0ZjMzOWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2OZYM_NnWFg--A_H2x3l_Y8FuOA3jMhXFvzolT91-Ac) ![image](https://private-user-images.githubusercontent.com/146911997/378075839-d0e15a92-92ab-40f1-960f-6ee66dcc5afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzkzNzUsIm5iZiI6MTcyOTMzOTA3NSwicGF0aCI6Ii8xNDY5MTE5OTcvMzc4MDc1ODM5LWQwZTE1YTkyLTkyYWItNDBmMS05NjBmLTZlZTY2ZGNjNWFmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMTU3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2VjOWYyY2FmZDk1OTllZTk1NDExOTUyODgyYjFmNjFmMTVkNWI5MWM3Zjg2YmY3MTc3ZWJlYjRlNzlmMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XQvg-TTSq4lJFpylw3Z2275nRXs0fBrRML1s2ut3kHw) Does these backend stuffs work with edit page? I got error 404.

I have this problem too.

2024-10-19 12:21 UTC, OmegaOoh requested changes

2024-10-19 12:21 UTC, OmegaOoh commented on activities/old_views.py
Dead Code. Delete it.

2024-10-19 12:21 UTC, OmegaOoh commented on activities/tests/test_create_activity.py
test participants raise an error:
`django.urls.exceptions.NoReverseMatch: Reverse for 'join' not found. 'join' is not a valid view function or pattern name.`

2024-10-19 12:21 UTC, OmegaOoh commented on mysite/urls.py
explains this change

2024-10-19 12:21 UTC, OmegaOoh commented on activities/views/util.py
Doesn't this need to be convert to REST?

2024-10-19 12:22 UTC, OmegaOoh commented
Another thing is, before the next review request please, merge the code from the main. I can't let you merge without reviewing it.

2024-10-19 12:37 UTC, opxz7148 commented on mysite/urls.py
Rest framwork has different default format. Need to set it to match with our format.

2024-10-19 13:07 UTC, OmegaOoh approved these changes
Looking good

2024-10-19 13:08 UTC, OmegaOoh requested changes
You need to merge from main before actually merge tho

2024-10-19 13:09 UTC, opxz7148 commented on mysite/urls.py
Oh my eyes are nut. I thought you comment on upper one. That thing is unnecessary will remove. 
<img width="1070" alt="Screenshot 2567-10-19 at 20 08 55" src="https://github.com/user-attachments/assets/7d9a16a6-fafe-44ad-92bc-43b7c71a72bc">

2024-10-19 13:18 UTC, opxz7148 commented on mysite/urls.py
Remove it on #[0cb0220](https://github.com/OmegaOoh/ku-tangtee/pull/84/commits/0cb02202a53f0bb14114e35b51b0f6d5d7d08084)

2024-10-19 14:01 UTC, Thanawas-Sirilertsathit approved these changes
The refresh button now appear

2024-10-19 14:05 UTC, OmegaOoh approved these changes

2024-10-19 14:05 UTC, merged