Show participant detail and profile picture
OmegaOoh/ku-tangtee pull request #93
Opened 2024-10-19 11:58 UTC by Thanawas-Sirilertsathit

- Profile picture and name of participants in edit page and detail page
- Show number of participant in edit page
- minor fix for long detail that will go out the box in detail page
- minor fix for card box in edit page when activity has many details, it will unable to scroll up to the top

2024-10-19 12:34 UTC, OmegaOoh requested changes

2024-10-19 12:34 UTC, OmegaOoh commented on activities/views.py
> +            return JsonResponse({"message": "Number of participants exceed the capacity.",
Please add the test for this

2024-10-20 06:05 UTC, Thanawas-Sirilertsathit commented
![image](https://github.com/user-attachments/assets/bbb41b03-0116-451d-b61f-601edf4fdecc)
@TeerapatTrepopsakulsin at least it should tell something that better than undefined. Edit activity restricted to host problem.

2024-10-20 11:39 UTC, OmegaOoh approved these changes
It does meet the acceptance criteria, but we still need to polish it further in the future.

2024-10-20 14:18 UTC, TeerapatTrepopsakulsin approved these changes
- Profile picture and name of participants in edit page and detail page _Approve_
- Show number of participant in edit page _Approve_
- minor fix for long detail that will go out the box in detail page _Approve_
- minor fix for card box in edit page when activity has many details, it will unable to scroll up to the top _Approve_

2024-10-20 14:19 UTC, opxz7148 approved these changes
Look good participant profile show properly.

2024-10-20 14:19 UTC, merged